title: 我的电子书库
description: 个人电子书收藏网站
baseurl: "/ebook-library"
url: ""

# 主题设置
theme: jekyll-theme-minimal

# 构建设置
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
