name: deploy

on:
  push:
    branches:
      - main # 设置触发部署的分支
  workflow_dispatch: # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Pages
        uses: actions/configure-pages@v3

      - name: 上传构建结果
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."

      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
